=== MobiFlight/MobiFlight-Connector/src/MobiFlightConnector/Joysticks/mfjoystick.schema.json
{
  "definitions": {},
  "$schema": "https://json-schema.org/draft/2019-09/schema#",
  "$id": "https://mobiflight.com/hid.schema.json",
  "title": "Root",
  "type": "object",
  "required": [ "InstanceName" ],
  "dependentRequired": {
    "Outputs": [ "VendorId", "ProductId" ]
  },
  "properties": {
    "InstanceName": {
      "$id": "#root/InstanceName",
      "title": "InstanceName",
      "type": "string",
      "description": "Instance name for the device. Required. This is used to match the definition with a connected device."
    },
    "Inputs": {
      "$id": "#root/Inputs",
      "title": "Inputs",
      "description": "List of inputs supported by the device. Optional.",
      "type": "array",
      "default": [],
      "items": {
        "$id": "#root/Inputs/items",
        "title": "Items",
        "type": "object",
        "required": [ "Id", "Label", "Type" ],
        "properties": {
          "Id": {
            "$id": "#root/Inputs/items/Id",
            "title": "Id",
            "description": "The input's unique identifier on the joystick. Required.",
            "type": "integer"
          },
          "Label": {
            "$id": "#root/Inputs/items/Label",
            "title": "Label",
            "description": "Friendly label for the input. Required.",
            "type": "string"
          },
          "Type": {
            "$id": "#root/Inputs/items/Type",
            "title": "Type",
            "description": "The input's type. Supported values: Button, Axis.",
            "type": "string",
            "enum": [ "Button", "Axis" ]
          }
        }
      }
    },
    "Outputs": {
      "$id": "#root/Outputs",
      "title": "Outputs",
      "description": "List of outputs supported by the device. Optional.",
      "type": "array",
      "default": [],
      "items": {
        "$id": "#root/Outputs/items",
        "title": "Items",
        "type": "object",
        "required": [ "Id", "Label", "Byte" ],
        "properties": {
          "Type": {
            "$id": "#root/Outputs/items/Type",
            "title": "Type",
            "description": "The output's type. Supported values: Output, Display. Defaults to 'Output' if not specified.",
            "type": "string",
            "enum": [ "Output", "LcdDisplay" ]
          },
          "Id": {
            "$id": "#root/Outputs/items/Id",
            "title": "Id",
            "description": "The unique identifier for the output. Required.",
            "type": "string"
          },
          "Label": {
            "$id": "#root/Outputs/items/Label",
            "title": "Label",
            "description": "Label for the output. Required.",
            "type": "string"
          },
          "Byte": {
            "$id": "#root/Outputs/items/Byte",
            "title": "Byte",
            "description": "Byte location of the output. Required for Output type, optional for Display type.",
            "type": "number"
          },
          "Bit": {
            "$id": "#root/Outputs/items/Bit",
            "title": "Bit",
            "description": "Bit location within the byte of the output. Required for Output type, optional for Display type.",
            "type": "number"
          },
          "Cols": {
            "$id": "#root/Outputs/items/Cols",
            "title": "Cols",
            "description": "Number of columns for the output. Required for Display type.",
            "type": "number"
          },
          "Lines": {
            "$id": "#root/Outputs/items/Lines",
            "title": "Lines",
            "description": "Number of lines for the output. Required for Display type.",
            "type": "number"
          }
        }
      }
    },
    "VendorId": {
      "$id": "#Root/VendorId",
      "title": "VendorId",
      "type": "string",
      "pattern": "^0x[0-9a-fA-F]+$",
      "description": "The device's USB VendorId as a hexadcimal, e.g. `0x123A`. Required if Outputs are provided."
    },
    "ProductId": {
      "$id": "#Root/ProductId",
      "title": "ProductId",
      "type": "string",
      "pattern": "^0x[0-9a-fA-F]+$",
      "description": "The device's USB ProductId as a hexadecimal, e.g. `0x234A`. Required if Outputs are provided."
    }
  }
}

=== MobiFlight/MobiFlight-Connector/src/MobiFlightConnector/Joysticks/logitech/logitech_radio_panel.joystick.json
{
  "$schema": "../mfjoystick.schema.json",
  "InstanceName": "Logitech Radio Panel",
  "VendorId": "0x06A3",
  "ProductId": "0x0D05",
  "Inputs": [
    { "Id": 0, "Type": "Button", "Label": "Upper COM1" },
    { "Id": 1, "Type": "Button", "Label": "Upper COM2" },
    { "Id": 2, "Type": "Button", "Label": "Upper NAV1" },
    { "Id": 3, "Type": "Button", "Label": "Upper NAV2" },
    { "Id": 4, "Type": "Button", "Label": "Upper ADF" },
    { "Id": 5, "Type": "Button", "Label": "Upper DME" },
    { "Id": 6, "Type": "Button", "Label": "Upper XPDR" },
    { "Id": 7, "Type": "Button", "Label": "Lower COM1" },
    { "Id": 8, "Type": "Button", "Label": "Lower COM2" },
    { "Id": 9, "Type": "Button", "Label": "Lower NAV1" },
    { "Id": 10, "Type": "Button", "Label": "Lower NAV2" },
    { "Id": 11, "Type": "Button", "Label": "Lower ADF" },
    { "Id": 12, "Type": "Button", "Label": "Lower DME" },
    { "Id": 13, "Type": "Button", "Label": "Lower XPDR" },
    { "Id": 14, "Type": "Button", "Label": "Upper ACT/STBY" },
    { "Id": 15, "Type": "Button", "Label": "Lower ACT/STBY" },
    { "Id": 16, "Type": "Button", "Label": "Upper inner CW" },
    { "Id": 17, "Type": "Button", "Label": "Upper inner CCW" },
    { "Id": 18, "Type": "Button", "Label": "Upper outer CW" },
    { "Id": 19, "Type": "Button", "Label": "Upper outer CCW" },
    { "Id": 20, "Type": "Button", "Label": "Lower inner CW" },
    { "Id": 21, "Type": "Button", "Label": "Lower inner CCW" },
    { "Id": 22, "Type": "Button", "Label": "Lower outer CW" },
    { "Id": 23, "Type": "Button", "Label": "Lower outer CCW" }
  ],
  "Outputs": [
    { "Id": "LCD COM1 ACTIVE", "Type": "LcdDisplay", "Label": "COM1 Active", "Byte": 1, "Cols": 5, "Lines": 1 },
    { "Id": "LCD COM1 STBY", "Type": "LcdDisplay", "Label": "COM1 Standby", "Byte": 6, "Cols": 5, "Lines": 1 },
    { "Id": "LCD COM2 ACTIVE", "Type": "LcdDisplay", "Label": "COM2 Active", "Byte": 11, "Cols": 5, "Lines": 1 },
    { "Id": "LCD COM2 STBY", "Type": "LcdDisplay", "Label": "COM2 Standby", "Byte": 16, "Cols": 5, "Lines": 1 }
  ]
}

=== MobiFlight/MobiFlight-Connector/src/MobiFlightConnector/Joysticks/moza/moza_mgx1000.joystick.json
{
  "$schema": "../mfjoystick.schema.json",
  "InstanceName": "MOZA MGX1000 Instrument Panel",
  "VendorId": "0x346E",
  "ProductId": "0x1304",
  "Inputs": [
    {
      "Id": 1,
      "Type": "Button",
      "Label": "AP"
    },
    {
      "Id": 2,
      "Type": "Button",
      "Label": "FD"
    },
    {
      "Id": 3,
      "Type": "Button",
      "Label": "HDG"
    },
    {
      "Id": 4,
      "Type": "Button",
      "Label": "ALT"
    },
    {
      "Id": 5,
      "Type": "Button",
      "Label": "NAV"
    },
    {
      "Id": 6,
      "Type": "Button",
      "Label": "VNV"
    },
    {
      "Id": 7,
      "Type": "Button",
      "Label": "APR"
    },
    {
      "Id": 8,
      "Type": "Button",
      "Label": "BC"
    },
    {
      "Id": 9,
      "Type": "Button",
      "Label": "VS"
    },
    {
      "Id": 10,
      "Type": "Button",
      "Label": "Nose UP"
    },
    {
      "Id": 11,
      "Type": "Button",
      "Label": "FLC"
    },
    {
      "Id": 12,
      "Type": "Button",
      "Label": "Nose DN"
    },
    {
      "Id": 13,
      "Type": "Button",
      "Label": "Direct To"
    },
    {
      "Id": 14,
      "Type": "Button",
      "Label": "MENU"
    },
    {
      "Id": 15,
      "Type": "Button",
      "Label": "FPL"
    },
    {
      "Id": 16,
      "Type": "Button",
      "Label": "PROC"
    },
    {
      "Id": 17,
      "Type": "Button",
      "Label": "CLR"
    },
    {
      "Id": 18,
      "Type": "Button",
      "Label": "ENT"
    },
    {
      "Id": 19,
      "Type": "Button",
      "Label": "Softkey 1"
    },
    {
      "Id": 20,
      "Type": "Button",
      "Label": "Softkey 2"
    },
    {
      "Id": 21,
      "Type": "Button",
      "Label": "Softkey 3"
    },
    {
      "Id": 22,
      "Type": "Button",
      "Label": "Softkey 4"
    },
    {
      "Id": 23,
      "Type": "Button",
      "Label": "Softkey 5"
    },
    {
      "Id": 24,
      "Type": "Button",
      "Label": "Softkey 6"
    },
    {
      "Id": 25,
      "Type": "Button",
      "Label": "Softkey 7"
    },
    {
      "Id": 26,
      "Type": "Button",
      "Label": "Softkey 8"
    },
    {
      "Id": 27,
      "Type": "Button",
      "Label": "Softkey 9"
    },
    {
      "Id": 28,
      "Type": "Button",
      "Label": "Softkey 10"
    },
    {
      "Id": 29,
      "Type": "Button",
      "Label": "Softkey 11"
    },
    {
      "Id": 30,
      "Type": "Button",
      "Label": "Softkey 12"
    },
    {
      "Id": 31,
      "Type": "Button",
      "Label": "NAV Swap"
    },
    {
      "Id": 32,
      "Type": "Button",
      "Label": "COM Swap"
    },
    {
      "Id": 33,
      "Type": "Button",
      "Label": "Nav Vol Down"
    },
    {
      "Id": 34,
      "Type": "Button",
      "Label": "Nav Vol Up"
    },
    {
      "Id": 35,
      "Type": "Button",
      "Label": "Nav Push ID"
    },
    {
      "Id": 36,
      "Type": "Button",
      "Label": "COM Vol Down"
    },
    {
      "Id": 37,
      "Type": "Button",
      "Label": "COM Vol Up"
    },
    {
      "Id": 38,
      "Type": "Button",
      "Label": "COM Push SQ"
    },
    {
      "Id": 39,
      "Type": "Button",
      "Label": "HDG Left"
    },
    {
      "Id": 40,
      "Type": "Button",
      "Label": "HDG Right"
    },
    {
      "Id": 41,
      "Type": "Button",
      "Label": "HDG Sync Push"
    },
    {
      "Id": 42,
      "Type": "Button",
      "Label": "NAV MHz Left"
    },
    {
      "Id": 43,
      "Type": "Button",
      "Label": "NAV MHz Right"
    },
    {
      "Id": 44,
      "Type": "Button",
      "Label": "NAV KHz Left"
    },
    {
      "Id": 45,
      "Type": "Button",
      "Label": "NAV KHz Right"
    },
    {
      "Id": 46,
      "Type": "Button",
      "Label": "NAV Select Push"
    },
    {
      "Id": 47,
      "Type": "Button",
      "Label": "ALT 1000 Left"
    },
    {
      "Id": 48,
      "Type": "Button",
      "Label": "ALT 1000 Right"
    },
    {
      "Id": 49,
      "Type": "Button",
      "Label": "ALT 100 Left"
    },
    {
      "Id": 50,
      "Type": "Button",
      "Label": "ALT 100 Right"
    },
    {
      "Id": 51,
      "Type": "Button",
      "Label": "ALT Push"
    },
    {
      "Id": 52,
      "Type": "Button",
      "Label": "COM MHz Left"
    },
    {
      "Id": 53,
      "Type": "Button",
      "Label": "COM MHz Right"
    },
    {
      "Id": 54,
      "Type": "Button",
      "Label": "COM KHz Left"
    },
    {
      "Id": 55,
      "Type": "Button",
      "Label": "COM KHz Right"
    },
    {
      "Id": 56,
      "Type": "Button",
      "Label": "COM Select Push"
    },
    {
      "Id": 57,
      "Type": "Button",
      "Label": "BARO Left"
    },
    {
      "Id": 58,
      "Type": "Button",
      "Label": "BARO Right"
    },
    {
      "Id": 59,
      "Type": "Button",
      "Label": "CRS Left"
    },
    {
      "Id": 60,
      "Type": "Button",
      "Label": "CRS Right"
    },
    {
      "Id": 61,
      "Type": "Button",
      "Label": "CRS Ctr Push"
    },
    {
      "Id": 62,
      "Type": "Button",
      "Label": "FMS Outer Left"
    },
    {
      "Id": 63,
      "Type": "Button",
      "Label": "FMS Outer Right"
    },
    {
      "Id": 64,
      "Type": "Button",
      "Label": "FMS Inner Left"
    },
    {
      "Id": 65,
      "Type": "Button",
      "Label": "FMS Inner Right"
    },
    {
      "Id": 66,
      "Type": "Button",
      "Label": "FMS PUSH CRSR"
    },
    {
      "Id": 67,
      "Type": "Button",
      "Label": "RANGE -"
    },
    {
      "Id": 68,
      "Type": "Button",
      "Label": "RANGE +"
    },
    {
      "Id": 69,
      "Type": "Button",
      "Label": "PAN Left"
    },
    {
      "Id": 70,
      "Type": "Button",
      "Label": "PAN Right"
    },
    {
      "Id": 71,
      "Type": "Button",
      "Label": "PAN Up"
    },
    {
      "Id": 72,
      "Type": "Button",
      "Label": "PAN Down"
    },
    {
      "Id": 73,
      "Type": "Button",
      "Label": "PAN Push"
    }
  ]
}

=== MobiFlight/MobiFlight-Connector/src/MobiFlightConnector/Joysticks/logitech/logitech_pz55.joystick.json
{
  "$schema": "../mfjoystick.schema.json",
  "InstanceName": "Logitech/Saitek Switch Panel PZ55",
  "VendorId": "0x06A3",
  "ProductId": "0x0D67",
  "Inputs": [
    { "Id": 0, "Type": "Button", "Label": "Master Battery" },
    { "Id": 1, "Type": "Button", "Label": "Master Alternator" },
    { "Id": 2, "Type": "Button", "Label": "Avionics Master" },
    { "Id": 3, "Type": "Button", "Label": "Fuel Pump" },
    { "Id": 4, "Type": "Button", "Label": "De-Ice" },
    { "Id": 5, "Type": "Button", "Label": "Pitot Heat" },
    { "Id": 6, "Type": "Button", "Label": "Cowl" },
    { "Id": 7, "Type": "Button", "Label": "Panel Light" },
    { "Id": 8, "Type": "Button", "Label": "Beacon Light" },
    { "Id": 9, "Type": "Button", "Label": "Navigation Light" },
    { "Id": 10, "Type": "Button", "Label": "Strobe Light" },
    { "Id": 11, "Type": "Button", "Label": "Taxi Light" },
    { "Id": 12, "Type": "Button", "Label": "Landing Light" },
    { "Id": 13, "Type": "Button", "Label": "Magneto Off" },
    { "Id": 14, "Type": "Button", "Label": "Magneto Right" },
    { "Id": 15, "Type": "Button", "Label": "Magneto Left" },
    { "Id": 16, "Type": "Button", "Label": "Magneto Both" },
    { "Id": 17, "Type": "Button", "Label": "Magneto Start" },
    { "Id": 18, "Type": "Button", "Label": "Gear Up" },
    { "Id": 19, "Type": "Button", "Label": "Gear Down" }
  ],
  "Outputs": [
    { "Id": "GEAR_NOSE_GREEN", "Label": "Gear Nose Green", "Byte": 1, "Bit": 0 },
    { "Id": "GEAR_NOSE_RED", "Label": "Gear Nose Red", "Byte": 1, "Bit": 3 },
    { "Id": "GEAR_LEFT_GREEN", "Label": "Gear Left Green", "Byte": 1, "Bit": 1 },
    { "Id": "GEAR_LEFT_RED", "Label": "Gear Left Red", "Byte": 1, "Bit": 4 },
    { "Id": "GEAR_RIGHT_GREEN", "Label": "Gear Right Green", "Byte": 1, "Bit": 2 },
    { "Id": "GEAR_RIGHT_RED", "Label": "Gear Right Red", "Byte": 1, "Bit": 5 }
  ]
}

=== MobiFlight/MobiFlight-Connector/src/MobiFlightConnector/Joysticks/winwing/winwing_rmp_left.joystick.json
{
  "$schema": "./mfjoystick.schema.json",
  "InstanceName": "WINCTRL 32 RMP L",
  "VendorId": "0x4098",
  "ProductId": "0xBB83",
  "Inputs": [
    {
      "Id": 1,
      "Type": "Button",
      "Label": "XFR"
    },
    {
      "Id": 2,
      "Type": "Button",
      "Label": "VHF1"
    },
    {
      "Id": 3,
      "Type": "Button",
      "Label": "VHF2"
    },
    {
      "Id": 4,
      "Type": "Button",
      "Label": "VHF3"
    },
    {
      "Id": 5,
      "Type": "Button",
      "Label": "LOAD"
    },
    {
      "Id": 6,
      "Type": "Button",
      "Label": "HF1"
    },
    {
      "Id": 7,
      "Type": "Button",
      "Label": "HF2"
    },
    {
      "Id": 8,
      "Type": "Button",
      "Label": "AM"
    },
    {
      "Id": 9,
      "Type": "Button",
      "Label": "NAV"
    },
    {
      "Id": 10,
      "Type": "Button",
      "Label": "VOR"
    },
    {
      "Id": 11,
      "Type": "Button",
      "Label": "iLS"
    },
    {
      "Id": 12,
      "Type": "Button",
      "Label": "GLS"
    },
    {
      "Id": 13,
      "Type": "Button",
      "Label": "MLS"
    },
    {
      "Id": 14,
      "Type": "Button",
      "Label": "ADF"
    },
    {
      "Id": 15,
      "Type": "Button",
      "Label": "OUTER KNOB DEC"
    },
    {
      "Id": 16,
      "Type": "Button",
      "Label": "OUTER KNOB INC"
    },
    {
      "Id": 17,
      "Type": "Button",
      "Label": "INNER KNOB DEC"
    },
    {
      "Id": 18,
      "Type": "Button",
      "Label": "INNER KNOB INC"
    },
    {
      "Id": 19,
      "Type": "Button",
      "Label": "FREQ KNOB PRESS"
    },
    {
      "Id": 20,
      "Type": "Button",
      "Label": "PWR ON"
    },
    {
      "Id": 21,
      "Type": "Button",
      "Label": "PWR OFF"
    }
  ]
}

=== MobiFlight/MobiFlight-Connector/src/MobiFlightConnector/Joysticks/logitech/logitech_multi_panel.joystick.json
{
  "$schema": "../mfjoystick.schema.json",
  "InstanceName": "Logitech Multi Panel",
  "VendorId": "0x06A3",
  "ProductId": "0x0D06",
  "Inputs": [
    { "Id": 0, "Type": "Button", "Label": "ALT Sel" },
    { "Id": 1, "Type": "Button", "Label": "VS Sel" },
    { "Id": 2, "Type": "Button", "Label": "IAS Sel" },
    { "Id": 3, "Type": "Button", "Label": "HDG Sel" },
    { "Id": 4, "Type": "Button", "Label": "CRS Sel" },

    { "Id": 5, "Type": "Button", "Label": "Encoder +" },
    { "Id": 6, "Type": "Button", "Label": "Encoder -" },

    { "Id": 7, "Type": "Button", "Label": "AP" },
    { "Id": 8, "Type": "Button", "Label": "HDG" },
    { "Id": 9, "Type": "Button", "Label": "NAV" },
    { "Id": 10, "Type": "Button", "Label": "IAS" },
    { "Id": 11, "Type": "Button", "Label": "ALT" },
    { "Id": 12, "Type": "Button", "Label": "VS" },
    { "Id": 13, "Type": "Button", "Label": "APR" },
    { "Id": 14, "Type": "Button", "Label": "REV" },

    { "Id": 15, "Type": "Button", "Label": "A/T ARM" },

    { "Id": 16, "Type": "Button", "Label": "FLAPS UP" },
    { "Id": 17, "Type": "Button", "Label": "FLAPS DOWN" },

    { "Id": 18, "Type": "Button", "Label": "PITCH DOWN" },
    { "Id": 19, "Type": "Button", "Label": "PITCH UP" }
  ],
  "Outputs": [
    { "Id": "AP",  "Label": "AP",  "Byte": 11, "Bit": 0 },
    { "Id": "HDG", "Label": "HDG", "Byte": 11, "Bit": 1 },
    { "Id": "NAV", "Label": "NAV", "Byte": 11, "Bit": 2 },
    { "Id": "IAS", "Label": "IAS", "Byte": 11, "Bit": 3 },
    { "Id": "ALT", "Label": "ALT", "Byte": 11, "Bit": 4 },
    { "Id": "VS",  "Label": "VS",  "Byte": 11, "Bit": 5 },
    { "Id": "APR", "Label": "APR", "Byte": 11, "Bit": 6 },
    { "Id": "REV", "Label": "REV", "Byte": 11, "Bit": 7 },

    { "Id": "LCD ALT", "Type": "LcdDisplay", "Label": "LCD Alt", "Byte": 1, "Cols": 5, "Lines": 1 },
    { "Id": "LCD VS", "Type": "LcdDisplay", "Label": "LCD VS", "Byte": 1, "Cols": 5, "Lines": 1 },
    { "Id": "LCD IAS", "Type": "LcdDisplay", "Label": "LCD IAS", "Byte": 1, "Cols": 3, "Lines": 1 },
    { "Id": "LCD HDG", "Type": "LcdDisplay", "Label": "LCD HDG", "Byte": 1, "Cols": 3, "Lines": 1 },
    { "Id": "LCD CRS", "Type": "LcdDisplay", "Label": "LCD CRS", "Byte": 1, "Cols": 3, "Lines": 1 }
  ]
}

=== MobiFlight/MobiFlight-Connector/src/MobiFlightConnector/Joysticks/wingflex/wingflex_gmp.joystick.json
{
  "$schema": "./mfjoystick.schema.json",
  "InstanceName": "WINGFLEX GMP",
  "VendorId": "0xC687",
  "ProductId": "0xB217",
  "Inputs": [
    {
      "Id": 1,
      "Type": "Button",
      "Label": "Brake Fan Key"
    },
    {
      "Id": 2,
      "Type": "Button",
      "Label": "AutoBrake Low Key"
    },
    {
      "Id": 3,
      "Type": "Button",
      "Label": "AutoBrake Medium Key"
    },
    {
      "Id": 4,
      "Type": "Button",
      "Label": "AutoBrake Max Key"
    },
    {
      "Id": 5,
      "Type": "Button",
      "Label": "Terrain On ND Key"
    },
    {
      "Id": 6,
      "Type": "Button",
      "Label": "Anti Skid Switch"
    },
    {
      "Id": 7,
      "Type": "Button",
      "Label": "RST Encoder Left"
    },
    {
      "Id": 8,
      "Type": "Button",
      "Label": "RST Encoder Right"
    },
    {
      "Id": 9,
      "Type": "Button",
      "Label": "RST Encoder Press"
    },
    {
      "Id": 10,
      "Type": "Button",
      "Label": "CHR Encoder Left"
    },
    {
      "Id": 11,
      "Type": "Button",
      "Label": "CHR Encoder Right"
    },
    {
      "Id": 12,
      "Type": "Button",
      "Label": "CHR Encoder Press"
    },
    {
      "Id": 13,
      "Type": "Button",
      "Label": "SET Encoder Left"
    },
    {
      "Id": 14,
      "Type": "Button",
      "Label": "SET Encoder Right"
    },
    {
      "Id": 15,
      "Type": "Button",
      "Label": "SET Encoder Press"
    },
    {
      "Id": 16,
      "Type": "Button",
      "Label": "Power On"
    },
    {
      "Id": 17,
      "Type": "Button",
      "Label": "GPS"
    },
    {
      "Id": 18,
      "Type": "Button",
      "Label": "GPS - INT"
    },
    {
      "Id": 19,
      "Type": "Button",
      "Label": "GPS - SET"
    },
    {
      "Id": 20,
      "Type": "Button",
      "Label": "RUN"
    },
    {
      "Id": 21,
      "Type": "Button",
      "Label": "RUN - STP"
    },
    {
      "Id": 22,
      "Type": "Button",
      "Label": "RUN - RST"
    },
    {
      "Id": 23,
      "Type": "Button",
      "Label": "Landing Gear Handle UP"
    },
    {
      "Id": 24,
      "Type": "Button",
      "Label": "Landing Gear Handle DOWN"
    },
    {
      "Id": 48,
      "Type": "Axis",
      "Label": "Landing Gear Axis"
    },
    {
      "Id": 49,
      "Type": "Axis",
      "Label": "Light Sensor"
    }
  ],
  "Outputs": [
    {
      "Label": "LDG Gear 1 UNLK",
      "Id": "ldg.gear1.unlk",
      "Byte": 1,
      "Bit": 0
    },
    {
      "Label": "LDG Gear 1 Arrow",
      "Id": "ldg.gear1.arrow",
      "Byte": 1,
      "Bit": 1
    },
    {
      "Label": "LDG Gear 2 UNLK",
      "Id": "ldg.gear2.unlk",
      "Byte": 1,
      "Bit": 2
    },
    {
      "Label": "LDG Gear 2 Arrow",
      "Id": "ldg.gear2.arrow",
      "Byte": 1,
      "Bit": 3
    },
    {
      "Label": "LDG Gear 3 UNLK",
      "Id": "ldg.gear3.unlk",
      "Byte": 1,
      "Bit": 4
    },
    {
      "Label": "LDG Gear 3 Arrow",
      "Id": "ldg.gear3.arrow",
      "Byte": 1,
      "Bit": 5
    },
    {
      "Label": "Brake Fan HOT",
      "Id": "brakefan.hot",
      "Byte": 1,
      "Bit": 6
    },
    {
      "Label": "Brake Fan ON",
      "Id": "brakefan.on",
      "Byte": 1,
      "Bit": 7
    },
    {
      "Label": "AutoBrk Low DECEL",
      "Id": "autobrk.low.decel",
      "Byte": 2,
      "Bit": 0
    },
    {
      "Label": "AutoBrk Low ON",
      "Id": "autobrk.low.on",
      "Byte": 2,
      "Bit": 1
    },
    {
      "Label": "AutoBrk Med DECEL",
      "Id": "autobrk.med.decel",
      "Byte": 2,
      "Bit": 2
    },
    {
      "Label": "AutoBrk Med ON",
      "Id": "autobrk.med.on",
      "Byte": 2,
      "Bit": 3
    },
    {
      "Label": "AutoBrk Max DECEL",
      "Id": "autobrk.max.decel",
      "Byte": 2,
      "Bit": 4
    },
    {
      "Label": "AutoBrk Max ON",
      "Id": "autobrk.max.on",
      "Byte": 2,
      "Bit": 5
    },
    {
      "Label": "TERR ON ND ON",
      "Id": "terr.on.nd",
      "Byte": 2,
      "Bit": 6
    },
    {
      "Label": "LDG Gear Red Arrow",
      "Id": "gear.red.arrow",
      "Byte": 2,
      "Bit": 7
    },
    {
      "Label": "Backlight Brightness",
      "Id": "backlight.brightness",
      "Byte": 3,
      "Bit": 0
    },
    {
      "Label": "Key Light Brightness",
      "Id": "keylight.brightness",
      "Byte": 4,
      "Bit": 0
    },
    {
      "Label": "Screen Brightness",
      "Id": "screen.brightness",
      "Byte": 5,
      "Bit": 0
    },
    {
      "Label": "Cold And Dark",
      "Id": "cold.and.dark",
      "Byte": 6,
      "Bit": 0
    },
    {
      "Label": "ANN LT Test",
      "Id": "ann.lt.test",
      "Byte": 6,
      "Bit": 1
    },
    {
      "Label": "Clock Mode",
      "Id": "clock.mode",
      "Byte": 6,
      "Bit": 2
    },
    {
      "Label": "CHR Colon",
      "Id": "chr.colon",
      "Byte": 6,
      "Bit": 3
    },
    {
      "Label": "UTC Colon Left",
      "Id": "utc.colon.left",
      "Byte": 6,
      "Bit": 4
    },
    {
      "Label": "UTC Colon Right",
      "Id": "utc.colon.right",
      "Byte": 6,
      "Bit": 5
    },
    {
      "Label": "ET Colon",
      "Id": "et.colon",
      "Byte": 6,
      "Bit": 6
    },
    {
      "Label": "Clock brightness",
      "Id": "clock.brightness",
      "Byte": 7,
      "Bit": 0
    },
    {
      "Label": "Chrono",
      "Id": "chrono.lcd",
      "Type": "LcdDisplay",
      "Byte": 8,
      "Cols": 4,
      "Lines": 1
    },
    {
      "Label": "UTC",
      "Id": "utc.lcd",
      "Type": "LcdDisplay",
      "Byte": 12,
      "Cols": 6,
      "Lines": 1
    },
    {
      "Label": "ET",
      "Id": "et.lcd",
      "Type": "LcdDisplay",
      "Byte": 18,
      "Cols": 4,
      "Lines": 1
    },
    {
      "Label": "Left brake pressure",
      "Id": "brake.press.left",
      "Type": "LcdDisplay",
      "Byte": 22,
      "Cols": 4,
      "Lines": 1
    },
    {
      "Label": "Right brake pressure",
      "Id": "brake.press.right",
      "Type": "LcdDisplay",
      "Byte": 24,
      "Cols": 4,
      "Lines": 1
    },
    {
      "Label": "Brake accumulator pressure",
      "Id": "brake.press.accu",
      "Type": "LcdDisplay",
      "Byte": 26,
      "Cols": 4,
      "Lines": 1
    }
  ]
}
