=== MobiFlight/MobiFlight-Connector/src/MobiFlightConnector/Joysticks/mfjoystick.schema.json
{
  "definitions": {},
  "$schema": "https://json-schema.org/draft/2019-09/schema#",
  "$id": "https://mobiflight.com/hid.schema.json",
  "title": "Root",
  "type": "object",
  "required": [ "InstanceName" ],
  "dependentRequired": {
    "Outputs": [ "VendorId", "ProductId" ]
  },
  "properties": {
    "InstanceName": {
      "$id": "#root/InstanceName",
      "title": "InstanceName",
      "type": "string",
      "description": "Instance name for the device. Required. This is used to match the definition with a connected device."
    },
    "Inputs": {
      "$id": "#root/Inputs",
      "title": "Inputs",
      "description": "List of inputs supported by the device. Optional.",
      "type": "array",
      "default": [],
      "items": {
        "$id": "#root/Inputs/items",
        "title": "Items",
        "type": "object",
        "required": [ "Id", "Label", "Type" ],
        "properties": {
          "Id": {
            "$id": "#root/Inputs/items/Id",
            "title": "Id",
            "description": "The input's unique identifier on the joystick. Required.",
            "type": "integer"
          },
          "Label": {
            "$id": "#root/Inputs/items/Label",
            "title": "Label",
            "description": "Friendly label for the input. Required.",
            "type": "string"
          },
          "Type": {
            "$id": "#root/Inputs/items/Type",
            "title": "Type",
            "description": "The input's type. Supported values: Button, Axis.",
            "type": "string",
            "enum": [ "Button", "Axis" ]
          }
        }
      }
    },
    "Outputs": {
      "$id": "#root/Outputs",
      "title": "Outputs",
      "description": "List of outputs supported by the device. Optional.",
      "type": "array",
      "default": [],
      "items": {
        "$id": "#root/Outputs/items",
        "title": "Items",
        "type": "object",
        "required": [ "Id", "Label", "Byte" ],
        "properties": {
          "Type": {
            "$id": "#root/Outputs/items/Type",
            "title": "Type",
            "description": "The output's type. Supported values: Output, Display. Defaults to 'Output' if not specified.",
            "type": "string",
            "enum": [ "Output", "LcdDisplay" ]
          },
          "Id": {
            "$id": "#root/Outputs/items/Id",
            "title": "Id",
            "description": "The unique identifier for the output. Required.",
            "type": "string"
          },
          "Label": {
            "$id": "#root/Outputs/items/Label",
            "title": "Label",
            "description": "Label for the output. Required.",
            "type": "string"
          },
          "Byte": {
            "$id": "#root/Outputs/items/Byte",
            "title": "Byte",
            "description": "Byte location of the output. Required for Output type, optional for Display type.",
            "type": "number"
          },
          "Bit": {
            "$id": "#root/Outputs/items/Bit",
            "title": "Bit",
            "description": "Bit location within the byte of the output. Required for Output type, optional for Display type.",
            "type": "number"
          },
          "Cols": {
            "$id": "#root/Outputs/items/Cols",
            "title": "Cols",
            "description": "Number of columns for the output. Required for Display type.",
            "type": "number"
          },
          "Lines": {
            "$id": "#root/Outputs/items/Lines",
            "title": "Lines",
            "description": "Number of lines for the output. Required for Display type.",
            "type": "number"
          }
        }
      }
    },
    "VendorId": {
      "$id": "#Root/VendorId",
      "title": "VendorId",
      "type": "string",
      "pattern": "^0x[0-9a-fA-F]+$",
      "description": "The device's USB VendorId as a hexadcimal, e.g. `0x123A`. Required if Outputs are provided."
    },
    "ProductId": {
      "$id": "#Root/ProductId",
      "title": "ProductId",
      "type": "string",
      "pattern": "^0x[0-9a-fA-F]+$",
      "description": "The device's USB ProductId as a hexadecimal, e.g. `0x234A`. Required if Outputs are provided."
    }
  }
}

=== MobiFlight/MobiFlight-Connector/src/MobiFlightConnector/Joysticks/wingflex/wingflex_dap500.joystick.json
{
  "$schema": "./mfjoystick.schema.json",
  "InstanceName": "WINGFLEX DAP500",
  "VendorId": "0xC687",
  "ProductId": "0xB216",
  "Inputs": [
    {
      "Id": 1,
      "Type": "Button",
      "Label": "HDG Knob Left"
    },
    {
      "Id": 2,
      "Type": "Button",
      "Label": "HDG Knob Right"
    },
    {
      "Id": 3,
      "Type": "Button",
      "Label": "HDG Knob Push"
    },
    {
      "Id": 4,
      "Type": "Button",
      "Label": "Trim Wheel - Nose Down"
    },
    {
      "Id": 5,
      "Type": "Button",
      "Label": "Trim Wheel - Nose Up"
    },
    {
      "Id": 6,
      "Type": "Button",
      "Label": "ALT Knob Left"
    },
    {
      "Id": 7,
      "Type": "Button",
      "Label": "ALT Knob Right"
    },
    {
      "Id": 8,
      "Type": "Button",
      "Label": "ALT Knob Push"
    },
    {
      "Id": 9,
      "Type": "Button",
      "Label": "HDG"
    },
    {
      "Id": 10,
      "Type": "Button",
      "Label": "APR"
    },
    {
      "Id": 11,
      "Type": "Button",
      "Label": "NAV"
    },
    {
      "Id": 12,
      "Type": "Button",
      "Label": "TRK"
    },
    {
      "Id": 13,
      "Type": "Button",
      "Label": "AP"
    },
    {
      "Id": 14,
      "Type": "Button",
      "Label": "FD"
    },
    {
      "Id": 15,
      "Type": "Button",
      "Label": "LVL"
    },
    {
      "Id": 16,
      "Type": "Button",
      "Label": "YD"
    },
    {
      "Id": 17,
      "Type": "Button",
      "Label": "IAS"
    },
    {
      "Id": 18,
      "Type": "Button",
      "Label": "VNAV"
    },
    {
      "Id": 19,
      "Type": "Button",
      "Label": "VS"
    },
    {
      "Id": 20,
      "Type": "Button",
      "Label": "ALT"
    },
    {
      "Id": 48,
      "Type": "Axis",
      "Label": "Light Sensor"
    }
  ],
  "Outputs": [
    {
      "Label": "APR LED",
      "Id": "APR_LED",
      "Byte": 1,
      "Bit": 0
    },
    {
      "Label": "NAV LED",
      "Id": "NAV_LED",
      "Byte": 1,
      "Bit": 1
    },
    {
      "Label": "TRK LED",
      "Id": "TRK_LED",
      "Byte": 1,
      "Bit": 2
    },
    {
      "Label": "HDG LED",
      "Id": "HDG_LED",
      "Byte": 1,
      "Bit": 3
    },
    {
      "Label": "AP LED",
      "Id": "AP_LED",
      "Byte": 1,
      "Bit": 4
    },
    {
      "Label": "FD LED",
      "Id": "FD_LED",
      "Byte": 1,
      "Bit": 5
    },
    {
      "Label": "LVL LED",
      "Id": "LVL_LED",
      "Byte": 1,
      "Bit": 6
    },
    {
      "Label": "YD LED",
      "Id": "YD_LED",
      "Byte": 1,
      "Bit": 7
    },
    {
      "Label": "IAS LED",
      "Id": "IAS_LED",
      "Byte": 2,
      "Bit": 0
    },
    {
      "Label": "VNAV LED",
      "Id": "VNAV_LED",
      "Byte": 2,
      "Bit": 1
    },
    {
      "Label": "VS LED",
      "Id": "VS_LED",
      "Byte": 2,
      "Bit": 2
    },
    {
      "Label": "ALT LED",
      "Id": "ALT_LED",
      "Byte": 2,
      "Bit": 3
    },
    {
      "Label": "Backlight Brightness",
      "Id": "BACKLIGHT",
      "Byte": 3,
      "Bit": 0
    }
  ]
}

=== MobiFlight/MobiFlight-Connector/src/MobiFlightConnector/Joysticks/freejoy/freejoy.joystick.json
{
  "$schema": "./mfjoystick.schema.json",
  "InstanceName": "FreeJoy",
  "VendorId": "0x0483",
  "ProductId": "0x5757",
  "Outputs": [
    {
      "Label": "LED 0",
      "Id": "led.0",
      "Byte": 0,
      "Bit": 0
    },
    {
      "Label": "LED 1",
      "Id": "led.1",
      "Byte": 0,
      "Bit": 1
    },
    {
      "Label": "LED 2",
      "Id": "led.2",
      "Byte": 0,
      "Bit": 2
    },
    {
      "Label": "LED 3",
      "Id": "led.3",
      "Byte": 0,
      "Bit": 3
    },
    {
      "Label": "LED 4",
      "Id": "led.4",
      "Byte": 0,
      "Bit": 4
    },
    {
      "Label": "LED 5",
      "Id": "led.5",
      "Byte": 0,
      "Bit": 5
    },
    {
      "Label": "LED 6",
      "Id": "led.6",
      "Byte": 0,
      "Bit": 6
    },
    {
      "Label": "LED 7",
      "Id": "led.7",
      "Byte": 0,
      "Bit": 7
    },
    {
      "Label": "LED 8",
      "Id": "led.8",
      "Byte": 1,
      "Bit": 0
    },
    {
      "Label": "LED 9",
      "Id": "led.9",
      "Byte": 1,
      "Bit": 1
    },
    {
      "Label": "LED 10",
      "Id": "led.10",
      "Byte": 1,
      "Bit": 2
    },
    {
      "Label": "LED 11",
      "Id": "led.11",
      "Byte": 1,
      "Bit": 3
    },
    {
      "Label": "LED 12",
      "Id": "led.12",
      "Byte": 1,
      "Bit": 4
    },
    {
      "Label": "LED 13",
      "Id": "led.13",
      "Byte": 1,
      "Bit": 5
    },
    {
      "Label": "LED 14",
      "Id": "led.14",
      "Byte": 1,
      "Bit": 6
    },
    {
      "Label": "LED 15",
      "Id": "led.15",
      "Byte": 1,
      "Bit": 7
    },
    {
      "Label": "LED 16",
      "Id": "led.16",
      "Byte": 2,
      "Bit": 0
    },
    {
      "Label": "LED 17",
      "Id": "led.17",
      "Byte": 2,
      "Bit": 1
    },
    {
      "Label": "LED 18",
      "Id": "led.18",
      "Byte": 2,
      "Bit": 2
    },
    {
      "Label": "LED 19",
      "Id": "led.19",
      "Byte": 2,
      "Bit": 3
    },
    {
      "Label": "LED 20",
      "Id": "led.20",
      "Byte": 2,
      "Bit": 4
    },
    {
      "Label": "LED 21",
      "Id": "led.21",
      "Byte": 2,
      "Bit": 5
    },
    {
      "Label": "LED 22",
      "Id": "led.22",
      "Byte": 2,
      "Bit": 6
    },
    {
      "Label": "LED 23",
      "Id": "led.23",
      "Byte": 2,
      "Bit": 7
    }
  ]
}
