=== MobiFlight/MobiFlight-Connector/src/MobiFlightConnector/Joysticks/mfjoystick.schema.json
{
  "definitions": {},
  "$schema": "https://json-schema.org/draft/2019-09/schema#",
  "$id": "https://mobiflight.com/hid.schema.json",
  "title": "Root",
  "type": "object",
  "required": [ "InstanceName" ],
  "dependentRequired": {
    "Outputs": [ "VendorId", "ProductId" ]
  },
  "properties": {
    "InstanceName": {
      "$id": "#root/InstanceName",
      "title": "InstanceName",
      "type": "string",
      "description": "Instance name for the device. Required. This is used to match the definition with a connected device."
    },
    "Inputs": {
      "$id": "#root/Inputs",
      "title": "Inputs",
      "description": "List of inputs supported by the device. Optional.",
      "type": "array",
      "default": [],
      "items": {
        "$id": "#root/Inputs/items",
        "title": "Items",
        "type": "object",
        "required": [ "Id", "Label", "Type" ],
        "properties": {
          "Id": {
            "$id": "#root/Inputs/items/Id",
            "title": "Id",
            "description": "The input's unique identifier on the joystick. Required.",
            "type": "integer"
          },
          "Label": {
            "$id": "#root/Inputs/items/Label",
            "title": "Label",
            "description": "Friendly label for the input. Required.",
            "type": "string"
          },
          "Type": {
            "$id": "#root/Inputs/items/Type",
            "title": "Type",
            "description": "The input's type. Supported values: Button, Axis.",
            "type": "string",
            "enum": [ "Button", "Axis" ]
          }
        }
      }
    },
    "Outputs": {
      "$id": "#root/Outputs",
      "title": "Outputs",
      "description": "List of outputs supported by the device. Optional.",
      "type": "array",
      "default": [],
      "items": {
        "$id": "#root/Outputs/items",
        "title": "Items",
        "type": "object",
        "required": [ "Id", "Label", "Byte" ],
        "properties": {
          "Type": {
            "$id": "#root/Outputs/items/Type",
            "title": "Type",
            "description": "The output's type. Supported values: Output, Display. Defaults to 'Output' if not specified.",
            "type": "string",
            "enum": [ "Output", "LcdDisplay" ]
          },
          "Id": {
            "$id": "#root/Outputs/items/Id",
            "title": "Id",
            "description": "The unique identifier for the output. Required.",
            "type": "string"
          },
          "Label": {
            "$id": "#root/Outputs/items/Label",
            "title": "Label",
            "description": "Label for the output. Required.",
            "type": "string"
          },
          "Byte": {
            "$id": "#root/Outputs/items/Byte",
            "title": "Byte",
            "description": "Byte location of the output. Required for Output type, optional for Display type.",
            "type": "number"
          },
          "Bit": {
            "$id": "#root/Outputs/items/Bit",
            "title": "Bit",
            "description": "Bit location within the byte of the output. Required for Output type, optional for Display type.",
            "type": "number"
          },
          "Cols": {
            "$id": "#root/Outputs/items/Cols",
            "title": "Cols",
            "description": "Number of columns for the output. Required for Display type.",
            "type": "number"
          },
          "Lines": {
            "$id": "#root/Outputs/items/Lines",
            "title": "Lines",
            "description": "Number of lines for the output. Required for Display type.",
            "type": "number"
          }
        }
      }
    },
    "VendorId": {
      "$id": "#Root/VendorId",
      "title": "VendorId",
      "type": "string",
      "pattern": "^0x[0-9a-fA-F]+$",
      "description": "The device's USB VendorId as a hexadcimal, e.g. `0x123A`. Required if Outputs are provided."
    },
    "ProductId": {
      "$id": "#Root/ProductId",
      "title": "ProductId",
      "type": "string",
      "pattern": "^0x[0-9a-fA-F]+$",
      "description": "The device's USB ProductId as a hexadecimal, e.g. `0x234A`. Required if Outputs are provided."
    }
  }
}

=== MobiFlight/MobiFlight-Connector/Joysticks/wingflex/wingflex_fcucube.joystick.json
{
  "$schema": "./mfjoystick.schema.json",
  "InstanceName": "WINGFLEX FCU CUBE",
  "VendorId": "0xA316",
  "ProductId": "0xC787",
  "Inputs": [
    {
      "Id": 1,
      "Type": "Button",
      "Label": "SPD MACH Switch"
    },
    {
      "Id": 2,
      "Type": "Button",
      "Label": "SPD Knob Push"
    },
    {
      "Id": 3,
      "Type": "Button",
      "Label": "SPD Knob Pull"
    },
    {
      "Id": 4,
      "Type": "Button",
      "Label": "HDG TRK Switch"
    },
    {
      "Id": 5,
      "Type": "Button",
      "Label": "HDG Knob Push"
    },
    {
      "Id": 6,
      "Type": "Button",
      "Label": "HDG Knob Pull"
    },
    {
      "Id": 7,
      "Type": "Button",
      "Label": "ALT 100"
    },
    {
      "Id": 8,
      "Type": "Button",
      "Label": "ALT 1000"
    },
    {
      "Id": 9,
      "Type": "Button",
      "Label": "ALT Knob Push"
    },
    {
      "Id": 10,
      "Type": "Button",
      "Label": "ALT Knob Pull"
    },
    {
      "Id": 11,
      "Type": "Button",
      "Label": "VS Knob Push"
    },
    {
      "Id": 12,
      "Type": "Button",
      "Label": "VS Knob Pull"
    },
    {
      "Id": 13,
      "Type": "Button",
      "Label": "METRIC ALT"
    },
    {
      "Id": 14,
      "Type": "Button",
      "Label": "AP1"
    },
    {
      "Id": 15,
      "Type": "Button",
      "Label": "AP2"
    },
    {
      "Id": 16,
      "Type": "Button",
      "Label": "A/THR"
    },
    {
      "Id": 17,
      "Type": "Button",
      "Label": "LOC"
    },
    {
      "Id": 18,
      "Type": "Button",
      "Label": "EXPED"
    },
    {
      "Id": 19,
      "Type": "Button",
      "Label": "APPR"
    },
    {
      "Id": 20,
      "Type": "Button",
      "Label": "SPD Knob Rotate Left"
    },
    {
      "Id": 21,
      "Type": "Button",
      "Label": "SPD Knob Rotate Right"
    },
    {
      "Id": 22,
      "Type": "Button",
      "Label": "HDG Knob Rotate Left"
    },
    {
      "Id": 23,
      "Type": "Button",
      "Label": "HDG Knob Rotate Right"
    },
    {
      "Id": 24,
      "Type": "Button",
      "Label": "ALT Knob Rotate Left"
    },
    {
      "Id": 25,
      "Type": "Button",
      "Label": "ALT Knob Rotate Right"
    },
    {
      "Id": 26,
      "Type": "Button",
      "Label": "VS Knob Rotate Left"
    },
    {
      "Id": 27,
      "Type": "Button",
      "Label": "VS Knob Rotate Right"
    },
    {
      "Id": 48,
      "Type": "Axis",
      "Label": "Background Light Brightness"
    },
    {
      "Id": 49,
      "Type": "Axis",
      "Label": "LCD Light Brightness"
    }
  ],
  "Outputs": [
    {
      "Label": "LOC Signal",
      "Id": "LOC.signal",
      "Byte": 6,
      "Bit": 0
    },
    {
      "Label": "AP1 Signal",
      "Id": "AP1.signal",
      "Byte": 6,
      "Bit": 1
    },
    {
      "Label": "AP2 Signal",
      "Id": "AP2.signal",
      "Byte": 6,
      "Bit": 2
    },
    {
      "Label": "A/THR Signal",
      "Id": "ATHR.signal",
      "Byte": 6,
      "Bit": 3
    },
    {
      "Label": "EXPED Signal",
      "Id": "EXPED.signal",
      "Byte": 6,
      "Bit": 4
    },
    {
      "Label": "APPR Signal",
      "Id": "APPR.signal",
      "Byte": 6,
      "Bit": 5
    },
    {
      "Label": "SPD Managed",
      "Id": "SPD.managed",
      "Byte": 6,
      "Bit": 6
    },
    {
      "Label": "SPD Dashed",
      "Id": "SPD.dashed",
      "Byte": 6,
      "Bit": 7
    },
    {
      "Label": "HDG Managed",
      "Id": "HDG.managed",
      "Byte": 7,
      "Bit": 0
    },
    {
      "Label": "HDG Dashed",
      "Id": "HDG.dashed",
      "Byte": 7,
      "Bit": 1
    },
    {
      "Label": "ALT Managed",
      "Id": "ALT.managed",
      "Byte": 7,
      "Bit": 2
    },
    {
      "Label": "VS Dashed",
      "Id": "VS.dashed",
      "Byte": 7,
      "Bit": 3
    },
    {
      "Label": "SPD MACH Mode",
      "Id": "SPD.mach_mode",
      "Byte": 7,
      "Bit": 4
    },
    {
      "Label": "HDG V/S Mode",
      "Id": "HDG.vs_mode",
      "Byte": 7,
      "Bit": 5
    },
    {
      "Label": "Test Mode",
      "Id": "test_mode",
      "Byte": 7,
      "Bit": 6
    },
    {
      "Label": "Power",
      "Id": "power",
      "Byte": 8,
      "Bit": 0
    },
    {
      "Label": "Panel Brightness",
      "Id": "brightness.panel",
      "Byte": 11,
      "Bit": 0
    },
    {
      "Label": "Display Brightness",
      "Id": "brightness.display",
      "Byte": 12,
      "Bit": 0
    },
    {
      "Label": "SPD",
      "Id": "SPD.value",
      "Type": "LcdDisplay",
      "Byte": 15,
      "Cols": 5,
      "Lines": 1
    },
    {
      "Label": "HDG",
      "Id": "HDG.value",
      "Type": "LcdDisplay",
      "Byte": 17,
      "Cols": 3,
      "Lines": 1
    },
    {
      "Label": "ALT",
      "Id": "ALT.value",
      "Type": "LcdDisplay",
      "Byte": 19,
      "Cols": 5,
      "Lines": 1
    },
    {
      "Label": "V/S",
      "Id": "VS.value",
      "Type": "LcdDisplay",
      "Byte": 21,
      "Cols": 4,
      "Lines": 1
    }
  ]
}

=== MobiFlight/MobiFlight-Connector/src/MobiFlightConnector/Joysticks/wingflex/wingflex_rmpcube.joystick.json
{
  "$schema": "./mfjoystick.schema.json",
  "InstanceName": "RMP Cube",
  "VendorId": "0xA616",
  "ProductId": "0x5750",
  "Inputs": [
    {
      "Id": 1,
      "Type": "Button",
      "Label": "Transfer Key"
    },
    {
      "Id": 2,
      "Type": "Button",
      "Label": "VHF1 Key"
    },
    {
      "Id": 3,
      "Type": "Button",
      "Label": "VHF2 Key"
    },
    {
      "Id": 4,
      "Type": "Button",
      "Label": "VHF3 Key"
    },
    {
      "Id": 5,
      "Type": "Button",
      "Label": "LOAD Key"
    },
    {
      "Id": 6,
      "Type": "Button",
      "Label": "HF1 Key"
    },
    {
      "Id": 7,
      "Type": "Button",
      "Label": "HF2 Key"
    },
    {
      "Id": 8,
      "Type": "Button",
      "Label": "ATC Key"
    },
    {
      "Id": 9,
      "Type": "Button",
      "Label": "NAV Key"
    },
    {
      "Id": 10,
      "Type": "Button",
      "Label": "VOR Key"
    },
    {
      "Id": 11,
      "Type": "Button",
      "Label": "ILS Key"
    },
    {
      "Id": 12,
      "Type": "Button",
      "Label": "GLS Key"
    },
    {
      "Id": 13,
      "Type": "Button",
      "Label": "MLS Key"
    },
    {
      "Id": 14,
      "Type": "Button",
      "Label": "ADF Key"
    },
    {
      "Id": 15,
      "Type": "Button",
      "Label": "IDENT Key"
    },
    {
      "Id": 16,
      "Type": "Button",
      "Label": "Power On"
    },
    {
      "Id": 17,
      "Type": "Button",
      "Label": "Power Off"
    },
    {
      "Id": 18,
      "Type": "Button",
      "Label": "ATC MSG Key"
    },
    {
      "Id": 19,
      "Type": "Button",
      "Label": "AUTO LAND Key"
    },
    {
      "Id": 20,
      "Type": "Button",
      "Label": "Transponder - STBY"
    },
    {
      "Id": 21,
      "Type": "Button",
      "Label": "Transponder - ON"
    },
    {
      "Id": 22,
      "Type": "Button",
      "Label": "Transponder - AUTO"
    },
    {
      "Id": 23,
      "Type": "Button",
      "Label": "TCAS - STBY"
    },
    {
      "Id": 24,
      "Type": "Button",
      "Label": "TCAS - TA"
    },
    {
      "Id": 25,
      "Type": "Button",
      "Label": "TCAS - TA/RA"
    },
    {
      "Id": 26,
      "Type": "Button",
      "Label": "Small Knob - Turn Left"
    },
    {
      "Id": 27,
      "Type": "Button",
      "Label": "Small Knob - Turn Right"
    },
    {
      "Id": 28,
      "Type": "Button",
      "Label": "Big Knob - Turn Right"
    },
    {
      "Id": 29,
      "Type": "Button",
      "Label": "Big Knob - Turn Right"
    }
  ],
  "Outputs": [
    {
      "Label": "Transfer Light",
      "Id": "transfer.led",
      "Byte": 6,
      "Bit": 0
    },
    {
      "Label": "VHF1",
      "Id": "VHF1.led",
      "Byte": 6,
      "Bit": 1
    },
    {
      "Label": "VHF2",
      "Id": "VHF2.led",
      "Byte": 6,
      "Bit": 2
    },
    {
      "Label": "VHF3",
      "Id": "VHF3.led",
      "Byte": 6,
      "Bit": 3
    },
    {
      "Label": "LOAD",
      "Id": "LOAD.led",
      "Byte": 6,
      "Bit": 4
    },
    {
      "Label": "HF1",
      "Id": "HF1.led",
      "Byte": 6,
      "Bit": 5
    },
    {
      "Label": "SEL",
      "Id": "SEL.led",
      "Byte": 6,
      "Bit": 6
    },
    {
      "Label": "HF2",
      "Id": "HF2.led",
      "Byte": 6,
      "Bit": 7
    },
    {
      "Label": "ATC",
      "Id": "ATC.led",
      "Byte": 7,
      "Bit": 0
    },
    {
      "Label": "NAV",
      "Id": "NAV.led",
      "Byte": 7,
      "Bit": 1
    },
    {
      "Label": "VOR",
      "Id": "VOR.led",
      "Byte": 7,
      "Bit": 2
    },
    {
      "Label": "ILS",
      "Id": "ILS.led",
      "Byte": 7,
      "Bit": 3
    },
    {
      "Label": "GLS",
      "Id": "GLS.led",
      "Byte": 7,
      "Bit": 4
    },
    {
      "Label": "MLS",
      "Id": "MLS.led",
      "Byte": 7,
      "Bit": 5
    },
    {
      "Label": "ADF",
      "Id": "ADF.led",
      "Byte": 7,
      "Bit": 6
    },
    {
      "Label": "ATC MSG (upper)",
      "Id": "ATC.upper.led",
      "Byte": 7,
      "Bit": 7
    },
    {
      "Label": "AUTO LAND",
      "Id": "autoland.led",
      "Byte": 8,
      "Bit": 0
    },
    {
      "Label": "Left LCD Switch",
      "Id": "llcd.switch",
      "Byte": 8,
      "Bit": 1
    },
    {
      "Label": "Right LCD Switch",
      "Id": "rlcd.switch",
      "Byte": 8,
      "Bit": 2
    },
    {
      "Label": "Left Display - \"C\" Mode",
      "Id": "lcmode.switch",
      "Byte": 8,
      "Bit": 3
    },
    {
      "Label": "Right Display - \"C\" Mode",
      "Id": "rcmode.switch",
      "Byte": 8,
      "Bit": 4
    },
    {
      "Label": "Left Display - \"DATA\" Mode",
      "Id": "ldatamode.switch",
      "Byte": 8,
      "Bit": 5
    },
    {
      "Label": "Right Display - \"DATA\" Mode",
      "Id": "rdatamode.switch",
      "Byte": 8,
      "Bit": 6
    },
    {
      "Label": "ATC MSG (lower)",
      "Id": "ATC.lower.led",
      "Byte": 8,
      "Bit": 7
    },
    {
      "Label": "Display Brightness",
      "Id": "brightness.panel",
      "Byte": 11,
      "Bit": 0
    },
    {
      "Label": "Background Brightness",
      "Id": "brightness.display",
      "Byte": 12,
      "Bit": 0
    },
    {
      "Label": "Left Dot Position",
      "Id": "left.dot.pos",
      "Byte": 13,
      "Bit": 0
    },
    {
      "Label": "Right Dot Position",
      "Id": "right.dot.pos",
      "Byte": 14,
      "Bit": 0
    },
    {
      "Label": "Left Digits",
      "Id": "left.digits",
      "Byte": 15,
      "Bit": 0
    },
    {
      "Label": "Right Digits",
      "Id": "right.digits",
      "Byte": 16,
      "Bit": 0
    },
    {
      "Label": "Active Lcd",
      "Id": "active.lcd",
      "Type": "LcdDisplay",
      "Byte": 19,
      "Cols": 6,
      "Lines": 1
    },
    {
      "Label": "Standby Lcd",
      "Id": "standby.l.lcd",
      "Type": "LcdDisplay",
      "Byte": 23,
      "Cols": 6,
      "Lines": 1
    }
  ]
}

=== MobiFlight/MobiFlight-Connector/src/MobiFlightConnector/Joysticks/moza/moza_mb7f.joystick.json
{
  "$schema": "../mfjoystick.schema.json",
  "InstanceName": "MOZA MB7F MFCD Display",
  "VendorId": "0x346E",
  "ProductId": "0x1306",
  "Inputs": [
    { "Id": 1,  "Type": "Button", "Label": "1 Button" },
    { "Id": 2,  "Type": "Button", "Label": "2 Button" },
    { "Id": 3,  "Type": "Button", "Label": "3 Button" },
    { "Id": 4,  "Type": "Button", "Label": "4 Button" },
    { "Id": 5,  "Type": "Button", "Label": "5 Button" },
    { "Id": 6,  "Type": "Button", "Label": "6 Button" },
    { "Id": 7,  "Type": "Button", "Label": "7 Button" },
    { "Id": 8,  "Type": "Button", "Label": "8 Button" },
    { "Id": 9,  "Type": "Button", "Label": "9 Button" },
    { "Id": 10, "Type": "Button", "Label": ". Button" },
    { "Id": 11, "Type": "Button", "Label": "0 Button" },
    { "Id": 12, "Type": "Button", "Label": "+/- Button" },
    { "Id": 13, "Type": "Button", "Label": "A Button" },
    { "Id": 14, "Type": "Button", "Label": "B Button" },
    { "Id": 15, "Type": "Button", "Label": "C Button" },
    { "Id": 16, "Type": "Button", "Label": "D Button" },
    { "Id": 17, "Type": "Button", "Label": "E Button" },
    { "Id": 18, "Type": "Button", "Label": "F Button" },
    { "Id": 19, "Type": "Button", "Label": "G Button" },
    { "Id": 20, "Type": "Button", "Label": "H Button" },
    { "Id": 21, "Type": "Button", "Label": "I Button" },
    { "Id": 22, "Type": "Button", "Label": "J Button" },
    { "Id": 23, "Type": "Button", "Label": "K Button" },
    { "Id": 24, "Type": "Button", "Label": "L Button" },
    { "Id": 25, "Type": "Button", "Label": "M Button" },
    { "Id": 26, "Type": "Button", "Label": "N Button" },
    { "Id": 27, "Type": "Button", "Label": "O Button" },
    { "Id": 28, "Type": "Button", "Label": "P Button" },
    { "Id": 29, "Type": "Button", "Label": "Q Button" },
    { "Id": 30, "Type": "Button", "Label": "R Button" },
    { "Id": 31, "Type": "Button", "Label": "S Button" },
    { "Id": 32, "Type": "Button", "Label": "T Button" },
    { "Id": 33, "Type": "Button", "Label": "U Button" },
    { "Id": 34, "Type": "Button", "Label": "V Button" },
    { "Id": 35, "Type": "Button", "Label": "W Button" },
    { "Id": 36, "Type": "Button", "Label": "X Button" },
    { "Id": 37, "Type": "Button", "Label": "Y Button" },
    { "Id": 38, "Type": "Button", "Label": "Z Button" },
    { "Id": 39, "Type": "Button", "Label": "/ Button" },
    { "Id": 40, "Type": "Button", "Label": "SP Button" },
    { "Id": 41, "Type": "Button", "Label": "DEL Button" },
    { "Id": 42, "Type": "Button", "Label": "CLR Button" },
    { "Id": 43, "Type": "Button", "Label": "Line-Select-Key 1L" },
    { "Id": 44, "Type": "Button", "Label": "Line-Select-Key 2L" },
    { "Id": 45, "Type": "Button", "Label": "Line-Select-Key 3L" },
    { "Id": 46, "Type": "Button", "Label": "Line-Select-Key 4L" },
    { "Id": 47, "Type": "Button", "Label": "Line-Select-Key 5L" },
    { "Id": 48, "Type": "Button", "Label": "Line-Select-Key 6L" },
    { "Id": 49, "Type": "Button", "Label": "Line-Select-Key 1R" },
    { "Id": 50, "Type": "Button", "Label": "Line-Select-Key 2R" },
    { "Id": 51, "Type": "Button", "Label": "Line-Select-Key 3R" },
    { "Id": 52, "Type": "Button", "Label": "Line-Select-Key 4R" },
    { "Id": 53, "Type": "Button", "Label": "Line-Select-Key 5R" },
    { "Id": 54, "Type": "Button", "Label": "Line-Select-Key 6R" },
    { "Id": 55, "Type": "Button", "Label": "BRT Button" },
    { "Id": 56, "Type": "Button", "Label": "DIM Button" },
    { "Id": 57, "Type": "Button", "Label": "INIT REF Button" },
    { "Id": 58, "Type": "Button", "Label": "RTE Button" },
    { "Id": 59, "Type": "Button", "Label": "CLB Button" },
    { "Id": 60, "Type": "Button", "Label": "CRZ Button" },
    { "Id": 61, "Type": "Button", "Label": "DES Button" },
    { "Id": 62, "Type": "Button", "Label": "MENU Button" },
    { "Id": 63, "Type": "Button", "Label": "LEGS Button" },
    { "Id": 64, "Type": "Button", "Label": "DEP ARR Button" },
    { "Id": 65, "Type": "Button", "Label": "HOLD Button" },
    { "Id": 66, "Type": "Button", "Label": "PROG Button" },
    { "Id": 67, "Type": "Button", "Label": "N1 LIMIT Button" },
    { "Id": 68, "Type": "Button", "Label": "FIX Button" },
    { "Id": 69, "Type": "Button", "Label": "PREV PAGE Button" },
    { "Id": 70, "Type": "Button", "Label": "NEXT PAGE Button" },
    { "Id": 71, "Type": "Button", "Label": "EXEC Button" }
  ],
  "Outputs": [
    { "Label": "CALL", "Id": "CALL.led", "Byte": 0, "Bit": 0 },
    { "Label": "FAIL", "Id": "FAIL.led", "Byte": 0, "Bit": 1 },
    { "Label": "EXEC", "Id": "EXEC.led", "Byte": 0, "Bit": 2 },
    { "Label": "MSG",  "Id": "MSG.led",  "Byte": 0, "Bit": 3 },
    { "Label": "OFST", "Id": "OFST.led", "Byte": 0, "Bit": 4 }
  ]
}

=== MobiFlight/MobiFlight-Connector/src/MobiFlightConnector/Joysticks/moza/moza_fcd_mcdu.joystick.json
{
  "$schema": "../mfjoystick.schema.json",
  "InstanceName": "MOZA MA3F MFCD Display",
  "VendorId": "0x346E",
  "ProductId": "0x1305",
  "Inputs": [
    {
      "Id": 1,
      "Type": "Button",
      "Label": "Line-Select-Key 1L"
    },
    {
      "Id": 2,
      "Type": "Button",
      "Label": "Line-Select-Key 2L"
    },
    {
      "Id": 3,
      "Type": "Button",
      "Label": "Line-Select-Key 3L"
    },
    {
      "Id": 4,
      "Type": "Button",
      "Label": "Line-Select-Key 4L"
    },
    {
      "Id": 5,
      "Type": "Button",
      "Label": "Line-Select-Key 5L"
    },
    {
      "Id": 6,
      "Type": "Button",
      "Label": "Line-Select-Key 6L"
    },
    {
      "Id": 7,
      "Type": "Button",
      "Label": "Line-Select-Key 1R"
    },
    {
      "Id": 8,
      "Type": "Button",
      "Label": "Line-Select-Key 2R"
    },
    {
      "Id": 9,
      "Type": "Button",
      "Label": "Line-Select-Key 3R"
    },
    {
      "Id": 10,
      "Type": "Button",
      "Label": "Line-Select-Key 4R"
    },
    {
      "Id": 11,
      "Type": "Button",
      "Label": "Line-Select-Key 5R"
    },
    {
      "Id": 12,
      "Type": "Button",
      "Label": "Line-Select-Key 6R"
    },
    {
      "Id": 13,
      "Type": "Button",
      "Label": "DIR Button"
    },
    {
      "Id": 14,
      "Type": "Button",
      "Label": "PROG Button"
    },
    {
      "Id": 15,
      "Type": "Button",
      "Label": "PERF Button"
    },
    {
      "Id": 16,
      "Type": "Button",
      "Label": "INIT Button"
    },
    {
      "Id": 17,
      "Type": "Button",
      "Label": "DATA Button"
    },
    {
      "Id": 18,
      "Type": "Button",
      "Label": "Blank Button R"
    },
    {
      "Id": 19,
      "Type": "Button",
      "Label": "BRT Button"
    },
    {
      "Id": 20,
      "Type": "Button",
      "Label": "F-PLN Button"
    },
    {
      "Id": 21,
      "Type": "Button",
      "Label": "RAD NAV Button"
    },
    {
      "Id": 22,
      "Type": "Button",
      "Label": "FUEL PRED Button"
    },
    {
      "Id": 23,
      "Type": "Button",
      "Label": "SEC F-PLN Button"
    },
    {
      "Id": 24,
      "Type": "Button",
      "Label": "ATC COMM Button"
    },
    {
      "Id": 25,
      "Type": "Button",
      "Label": "MCDU MENU Button"
    },
    {
      "Id": 26,
      "Type": "Button",
      "Label": "DIM Button"
    },
    {
      "Id": 27,
      "Type": "Button",
      "Label": "AIRPORT Button"
    },
    {
      "Id": 28,
      "Type": "Button",
      "Label": "Blank Button L"
    },
    {
      "Id": 29,
      "Type": "Button",
      "Label": "Left-Arrow Button"
    },
    {
      "Id": 30,
      "Type": "Button",
      "Label": "Up-Arrow Button"
    },
    {
      "Id": 31,
      "Type": "Button",
      "Label": "Right-Arrow Button"
    },
    {
      "Id": 32,
      "Type": "Button",
      "Label": "Down-Arrow Button"
    },
    {
      "Id": 33,
      "Type": "Button",
      "Label": "1 Button"
    },
    {
      "Id": 34,
      "Type": "Button",
      "Label": "2 Button"
    },
    {
      "Id": 35,
      "Type": "Button",
      "Label": "3 Button"
    },
    {
      "Id": 36,
      "Type": "Button",
      "Label": "4 Button"
    },
    {
      "Id": 37,
      "Type": "Button",
      "Label": "5 Button"
    },
    {
      "Id": 38,
      "Type": "Button",
      "Label": "6 Button"
    },
    {
      "Id": 39,
      "Type": "Button",
      "Label": "7 Button"
    },
    {
      "Id": 40,
      "Type": "Button",
      "Label": "8 Button"
    },
    {
      "Id": 41,
      "Type": "Button",
      "Label": "9 Button"
    },
    {
      "Id": 42,
      "Type": "Button",
      "Label": ". Button"
    },
    {
      "Id": 43,
      "Type": "Button",
      "Label": "0 Button"
    },
    {
      "Id": 44,
      "Type": "Button",
      "Label": "+/- Button"
    },
    {
      "Id": 45,
      "Type": "Button",
      "Label": "A Button"
    },
    {
      "Id": 46,
      "Type": "Button",
      "Label": "B Button"
    },
    {
      "Id": 47,
      "Type": "Button",
      "Label": "C Button"
    },
    {
      "Id": 48,
      "Type": "Button",
      "Label": "D Button"
    },
    {
      "Id": 49,
      "Type": "Button",
      "Label": "E Button"
    },
    {
      "Id": 50,
      "Type": "Button",
      "Label": "F Button"
    },
    {
      "Id": 51,
      "Type": "Button",
      "Label": "G Button"
    },
    {
      "Id": 52,
      "Type": "Button",
      "Label": "H Button"
    },
    {
      "Id": 53,
      "Type": "Button",
      "Label": "I Button"
    },
    {
      "Id": 54,
      "Type": "Button",
      "Label": "J Button"
    },
    {
      "Id": 55,
      "Type": "Button",
      "Label": "K Button"
    },
    {
      "Id": 56,
      "Type": "Button",
      "Label": "L Button"
    },
    {
      "Id": 57,
      "Type": "Button",
      "Label": "M Button"
    },
    {
      "Id": 58,
      "Type": "Button",
      "Label": "N Button"
    },
    {
      "Id": 59,
      "Type": "Button",
      "Label": "O Button"
    },
    {
      "Id": 60,
      "Type": "Button",
      "Label": "P Button"
    },
    {
      "Id": 61,
      "Type": "Button",
      "Label": "Q Button"
    },
    {
      "Id": 62,
      "Type": "Button",
      "Label": "R Button"
    },
    {
      "Id": 63,
      "Type": "Button",
      "Label": "S Button"
    },
    {
      "Id": 64,
      "Type": "Button",
      "Label": "T Button"
    },
    {
      "Id": 65,
      "Type": "Button",
      "Label": "U Button"
    },
    {
      "Id": 66,
      "Type": "Button",
      "Label": "V Button"
    },
    {
      "Id": 67,
      "Type": "Button",
      "Label": "W Button"
    },
    {
      "Id": 68,
      "Type": "Button",
      "Label": "X Button"
    },
    {
      "Id": 69,
      "Type": "Button",
      "Label": "Y Button"
    },
    {
      "Id": 70,
      "Type": "Button",
      "Label": "Z Button"
    },
    {
      "Id": 71,
      "Type": "Button",
      "Label": "/ Button"
    },
    {
      "Id": 72,
      "Type": "Button",
      "Label": "SP Button"
    },
    {
      "Id": 73,
      "Type": "Button",
      "Label": "OVFY Button"
    },
    {
      "Id": 74,
      "Type": "Button",
      "Label": "CLR Button"
    }
  ],
  "Outputs": [
    {
      "Label": "FAIL",
      "Id": "FAIL.led",
      "Byte": 0,
      "Bit": 0
    },
    {
      "Label": "FM",
      "Id": "FM.led",
      "Byte": 0,
      "Bit": 1
    },
    {
      "Label": "MCDU",
      "Id": "MCDU.led",
      "Byte": 0,
      "Bit": 2
    },
    {
      "Label": "MENU",
      "Id": "MENU.led",
      "Byte": 0,
      "Bit": 3
    },
    {
      "Label": "FM1",
      "Id": "FM1.led",
      "Byte": 0,
      "Bit": 4
    },
    {
      "Label": "IND",
      "Id": "IND.led",
      "Byte": 0,
      "Bit": 5
    },
    {
      "Label": "RDY",
      "Id": "RDY.led",
      "Byte": 0,
      "Bit": 6
    },
    {
      "Label": "STATUS",
      "Id": "STATUS.led",
      "Byte": 0,
      "Bit": 7
    },
    {
      "Label": "FM2",
      "Id": "FM2.led",
      "Byte": 1,
      "Bit": 0
    }
  ]
}
