=== MobiFlight/MobiFlight-Connector/MobiFlightCore/Boards/mfboard.schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://mobiflight.com/mfboard.schema.json",
  "title": "Root",
  "type": "object",
  "required": ["Connection", "HardwareIds", "Info", "ModuleLimits", "Pins"],
  "properties": {
    "AvrDudeSettings": {
      "$id": "#root/AvrDudeSettings",
      "title": "Avrdudesettings",
      "type": "object",
      "description": "Settings for flashing Arduino devices with avrdude.",
      "required": ["BaudRate", "Device", "FirmwareBaseName", "Programmer"],
      "properties": {
        "BaudRate": {
          "$id": "#root/AvrDudeSettings/BaudRate",
          "title": "Baudrate",
          "description": "Baud rate to use with AvrDude.",
          "type": "string"
        },
        "Device": {
          "$id": "#root/AvrDudeSettings/Device",
          "title": "Device",
          "description": "AvrDude device type for the device.",
          "type": "string"
        },
        "FirmwareBaseName": {
          "$id": "#root/AvrDudeSettings/FirmwareBaseName",
          "title": "Firmwarebasename",
          "description": "Base name for firmware files. The final filename is of the form {FirmwareBaseName}_{Version}.hex.",
          "type": "string"
        },
        "Programmer": {
          "$id": "#root/AvrDudeSettings/Programmer",
          "title": "Programmer",
          "description": "AvrDude programmer to use for the device.",
          "type": "string"
        },
        "Timeout": {
          "$id": "#root/AvrDudeSettings/Timeout",
          "title": "Timeout",
          "description": "Number of milliseconds to wait before we assume the AvrDude process failed and has to get killed.",
          "type": "integer"
        }
      }
    },
    "Connection": {
      "$id": "#root/Connection",
      "title": "Connection",
      "description": "Connection-related settings for the board.",
      "type": "object",
      "required": [
        "ConnectionDelay",
        "DelayAfterFirmwareUpdate",
        "DtrEnable",
        "EEPROMSize",
        "ExtraConnectionRetry",
        "ForceResetOnFirmwareUpdate",
        "MessageSize"
      ],
      "properties": {
        "ConnectionDelay": {
          "$id": "#root/Connection/ConnectionDelay",
          "title": "Connectiondelay",
          "description": "Number of milliseconds to wait before loading the configuration after initially connecting to the board.",
          "type": "integer"
        },
        "DelayAfterFirmwareUpdate": {
          "$id": "#root/Connection/DelayAfterFirmwareUpdate",
          "title": "Delayafterfirmwareupdate",
          "description": "Number of milliseconds to wait after a firmware update before attempting to reconnect to the board.",
          "type": "integer"
        },
        "DtrEnable": {
          "$id": "#root/Connection/DtrEnable",
          "title": "Dtrenable",
          "description": "True if DTR should be enabled when connecting to the board over serial.",
          "type": "boolean"
        },
        "EEPROMSize": {
          "$id": "#root/Connection/EEPROMSize",
          "title": "Eepromsize",
          "description": "Maximum size of EEPROM storage, in bytes.",
          "type": "integer"
        },
        "ExtraConnectionRetry": {
          "$id": "#root/Connection/ExtraConnectionRetry",
          "title": "Extraconnectionretry",
          "description": "True if multiple attempts should be made when connecting to the board.",
          "type": "boolean"
        },
        "ForceResetOnFirmwareUpdate": {
          "$id": "#root/Connection/ForceResetOnFirmwareUpdate",
          "title": "Forceresetonfirmwareupdate",
          "description": "True if a force reset should be done to the board before attempting to upload the firmware.",
          "type": "boolean"
        },
        "MessageSize": {
          "$id": "#root/Connection/MessageSize",
          "title": "Messagesize",
          "description": "Maximum size of a CmdMessenger message, in bytes.",
          "type": "integer"
        }
      }
    },
    "HardwareIds": {
      "$id": "#root/HardwareIds",
      "title": "Hardwareids",
      "description": "A list of regular expressions of USB hardware IDs that use this board definition.",
      "type": "array",
      "default": [],
      "items": {
        "$id": "#root/HardwareIds/items",
        "title": "Items",
        "description": "A regular expression that should match a VID/PID.",
        "type": "string"
      }
    },
    "Info": {
      "$id": "#root/Info",
      "title": "Info",
      "description": "General board information properties.",
      "type": "object",
      "required": [
        "CanInstallFirmware",
        "FriendlyName",
        "LatestFirmwareVersion",
        "MobiFlightType"
      ],
      "properties": {
        "CanInstallFirmware": {
          "$id": "#root/Info/CanInstallFirmware",
          "title": "Caninstallfirmware",
          "description": "True if the board supports loading firmware via MobiFlight.",
          "type": "boolean"
        },
        "FriendlyName": {
          "$id": "#root/Info/FriendlyName",
          "title": "Friendlyname",
          "description": "The USB friendly name for the board as specified by the board manufacturer.",
          "type": "string"
        },
        "LatestFirmwareVersion": {
          "$id": "#root/Info/LatestFirmwareVersion",
          "title": "Latestfirmwareversion",
          "description": "The latest supported version of the firmware.",
          "type": "string"
        },
        "MobiFlightType": {
          "$id": "#root/Info/MobiFlightType",
          "title": "Mobiflighttype",
          "description": "The type of the board as provided by the MobiFlight firmware.",
          "type": "string"
        }
      }
    },
    "ModuleLimits": {
      "$id": "#root/ModuleLimits",
      "title": "Modulelimits",
      "description": "Maximum number of each type of module supported by the board.",
      "type": "object",
      "required": [
        "MaxAnalogInputs",
        "MaxButtons",
        "MaxEncoders",
        "MaxInputShifters",
        "MaxLcdI2C",
        "MaxLedSegments",
        "MaxOutputs",
        "MaxServos",
        "MaxSteppers",
        "MaxInputShifters",
        "MaxInputMultiplexer"
      ],
      "properties": {
        "MaxAnalogInputs": {
          "$id": "#root/ModuleLimits/MaxAnalogInputs",
          "title": "Maxanaloginputs",
          "description": "Maximum number of analog inputs supported by the board.",
          "type": "integer"
        },
        "MaxButtons": {
          "$id": "#root/ModuleLimits/MaxButtons",
          "title": "Maxbuttons",
          "description": "Maximum number of buttons supported by the board.",
          "type": "integer"
        },
        "MaxEncoders": {
          "$id": "#root/ModuleLimits/MaxEncoders",
          "title": "Maxencoders",
          "description": "Maximum number of encoders supported by the board.",
          "type": "integer"
        },
        "MaxLcdI2C": {
          "$id": "#root/ModuleLimits/MaxLcdI2C",
          "title": "Maxlcdi2c",
          "description": "Maximum number of I2C LCDs supported by the board.",
          "type": "integer"
        },
        "MaxLedSegments": {
          "$id": "#root/ModuleLimits/MaxLedSegments",
          "title": "Maxledsegments",
          "description": "Maximum number of LED segments supported by the board.",
          "type": "integer"
        },
        "MaxOutputs": {
          "$id": "#root/ModuleLimits/MaxOutputs",
          "title": "Maxoutputs",
          "description": "Maximum number of outputs supported by the board.",
          "type": "integer"
        },
        "MaxServos": {
          "$id": "#root/ModuleLimits/MaxServos",
          "title": "Maxservos",
          "description": "Maximum number of servos supported by the board.",
          "type": "integer"
        },
        "MaxSteppers": {
          "$id": "#root/ModuleLimits/MaxSteppers",
          "title": "Maxsteppers",
          "description": "Maximum number of steppers supported by the board.",
          "type": "integer"
        },
        "MaxShifters": {
          "$id": "#root/ModuleLimits/MaxShifters",
          "title": "Maxshifters",
          "description": "Maximum number of output shift registers supported by the board.",
          "type": "integer"
        },
        "MaxInputShifters": {
          "$id": "#root/ModuleLimits/MaxInputShifters",
          "title": "MaxInputShifters",
          "description": "Maximum number of input shift registers supported by the board.",
          "type": "integer"
        },
        "MaxInputMultiplexer": {
          "$id": "#root/ModuleLimits/MaxInputMultiplexer",
          "title": "MaxInputMuxes",
          "description": "Maximum number of digital input multiplexers supported by the board.",
          "type": "integer"
        }
      }
    },
    "Pins": {
      "$id": "#root/Pins",
      "title": "Pins",
      "description": "List of pins supported by the board.",
      "type": "array",
      "default": [],
      "items": {
        "$id": "#root/Pins/items",
        "title": "Items",
        "type": "object",
        "required": ["isAnalog", "isPWM", "isI2C", "Pin"],
        "properties": {
          "isAnalog": {
            "$id": "#root/Pins/items/isAnalog",
            "title": "Isanalog",
            "description": "True if the pin is an analog pin.",
            "type": "boolean"
          },
          "isPWM": {
            "$id": "#root/Pins/items/isPWM",
            "title": "Ispwm",
            "description": "True if the pin supports PWM.",
            "type": "boolean"
          },
          "isI2C": {
            "$id": "#root/Pins/items/isI2C",
            "title": "Isi2c",
            "description": "True if the pin is used for I2C communication.",
            "type": "boolean"
          },
          "Name": {
            "$id": "#root/Pins/items/Name",
            "title": "Name",
            "description": "Optional display name for the pin.",
            "examples": ["A1"],
            "type": "string"
          },
          "Pin": {
            "$id": "#root/Pins/items/Pin",
            "title": "Pin",
            "description": "The number for the pin on the board.",
            "type": "integer"
          }
        }
      }
    }
  }
}

=== MobiFlight/MobiFlight-Connector/src/MobiFlightConnector/Community/rowsfire/boards/rowsfire_gd32.board.json
{
  "$schema": "../../../Boards/mfboard.schema.json",
  "HardwareIds": [
    "^VID_1A86&PID_7523"
  ],
  "Info": {
    "MobiFlightType": "Rowsfire GD32",
    "MobiFlightTypeLabel": "Rowsfire GD32",
    "FriendlyName": "Rowsfire GD32 Panel",
    "CanInstallFirmware": false,
    "CanResetBoard": false,
    "FirmwareBaseName": "Rowsfire_GD32",
    "FirmwareExtension": "hex",
    "LatestFirmwareVersion": "1.0.0",
    "CustomDeviceTypes": [],
    "Community": {
      "Project": "Rowsfire",
      "Website": "https://rowsfire.com/",
      "Docs": "https://rowsfire.com/",
      "Support": "https://rowsfire.com/"
    }
  },
  "Connection": {
    "ConnectionDelay": 1250,
    "DelayAfterFirmwareUpdate": 0,
    "DtrEnable": false,
    "EEPROMSize": 1496,
    "ExtraConnectionRetry": true,
    "ForceResetOnFirmwareUpdate": false,
    "MessageSize": 90,
    "TimeoutForFirmwareUpdate": 60000
  },
  "ModuleLimits": {
    "MaxAnalogInputs": 16,
    "MaxButtons": 68,
    "MaxEncoders": 20,
    "MaxInputShifters": 6,
    "MaxInputMultiplexer": 6,
    "MaxLcdI2C": 4,
    "MaxLedSegments": 6,
    "MaxOutputs": 68,
    "MaxServos": 12,
    "MaxShifters": 6,
    "MaxSteppers": 10,
    "MaxCustomDevices": 0
  },
  "Pins": [
    {
      "Pin": 0,
      "Name": "PE2",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": false
    },
    {
      "Pin": 1,
      "Name": "PE3 (A107PRO: Output PWM)",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": true
    },
    {
      "Pin": 2,
      "Name": "PE4",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": false
    },
    {
      "Pin": 3,
      "Name": "PE5",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": false
    },
    {
      "Pin": 4,
      "Name": "PE6",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": false
    },
    {
      "Pin": 5,
      "Name": "PC13",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": false
    },
    {
      "Pin": 6,
      "Name": "PC14",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": false
    },
    {
      "Pin": 7,
      "Name": "PC15",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": false
    },
    {
      "Pin": 8,
      "Name": "PB2",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": false
    },
    {
      "Pin": 9,
      "Name": "PE7",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": false
    },
    {
      "Pin": 10,
      "Name": "PE8",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": true
    },
    {
      "Pin": 11,
      "Name": "PE9",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": true
    },
    {
      "Pin": 12,
      "Name": "PE10",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": true
    },
    {
      "Pin": 13,
      "Name": "PE11",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": true
    },
    {
      "Pin": 14,
      "Name": "PE12",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": true
    },
    {
      "Pin": 15,
      "Name": "PE13",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": true
    },
    {
      "Pin": 16,
      "Name": "PE14",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": true
    },
    {
      "Pin": 17,
      "Name": "PE15",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": false
    },
    {
      "Pin": 18,
      "Name": "PB10",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": true
    },
    {
      "Pin": 19,
      "Name": "PB11",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": true
    },
    {
      "Pin": 20,
      "Name": "PB12",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": false
    },
    {
      "Pin": 21,
      "Name": "PB13",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": true
    },
    {
      "Pin": 22,
      "Name": "PB14",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": true
    },
    {
      "Pin": 23,
      "Name": "PB15",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": true
    },
    {
      "Pin": 24,
      "Name": "PD8",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": false
    },
    {
      "Pin": 25,
      "Name": "PD9",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": false
    },
    {
      "Pin": 26,
      "Name": "PD10",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": false
    },
    {
      "Pin": 27,
      "Name": "PD11",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": false
    },
    {
      "Pin": 28,
      "Name": "PD12",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": true
    },
    {
      "Pin": 29,
      "Name": "PD13",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": true
    },
    {
      "Pin": 30,
      "Name": "PD14",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": true
    },
    {
      "Pin": 31,
      "Name": "PD15",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": true
    },
    {
      "Pin": 32,
      "Name": "PC6",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": true
    },
    {
      "Pin": 33,
      "Name": "PC7",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": true
    },
    {
      "Pin": 34,
      "Name": "PC8",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": true
    },
    {
      "Pin": 35,
      "Name": "PC9",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": true
    },
    {
      "Pin": 36,
      "Name": "PA8",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": true
    },
    {
      "Pin": 37,
      "Name": "PA9 (USART0_TX reserved)",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": false
    },
    {
      "Pin": 38,
      "Name": "PA10 (USART0_RX reserved)",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": false
    },
    {
      "Pin": 39,
      "Name": "PA11",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": true
    },
    {
      "Pin": 40,
      "Name": "PA12 (A107PRO: Analog Input)",
      "isAnalog": true,
      "isI2C": false,
      "isPWM": false
    },
    {
      "Pin": 41,
      "Name": "PA13 (SWDIO)",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": false
    },
    {
      "Pin": 42,
      "Name": "PA14 (SWCLK)",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": false
    },
    {
      "Pin": 43,
      "Name": "PA15 (JTDI/SPI2_NSS)",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": true
    },
    {
      "Pin": 44,
      "Name": "PC10",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": false
    },
    {
      "Pin": 45,
      "Name": "PC11",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": false
    },
    {
      "Pin": 46,
      "Name": "PC12",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": false
    },
    {
      "Pin": 47,
      "Name": "PD0",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": false
    },
    {
      "Pin": 48,
      "Name": "PD1",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": false
    },
    {
      "Pin": 49,
      "Name": "PD2",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": false
    },
    {
      "Pin": 50,
      "Name": "PD3",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": false
    },
    {
      "Pin": 51,
      "Name": "PD4",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": false
    },
    {
      "Pin": 52,
      "Name": "PD5",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": false
    },
    {
      "Pin": 53,
      "Name": "PD6",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": false
    },
    {
      "Pin": 54,
      "Name": "PD7",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": false
    },
    {
      "Pin": 55,
      "Name": "PB3 (JTDO/SPI2_SCK)",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": true
    },
    {
      "Pin": 56,
      "Name": "PB4 (NJTRST/SPI2_MISO)",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": true
    },
    {
      "Pin": 57,
      "Name": "PB5",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": true
    },
    {
      "Pin": 58,
      "Name": "PB6",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": true
    },
    {
      "Pin": 59,
      "Name": "PB7",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": true
    },
    {
      "Pin": 60,
      "Name": "PB8 (I2C0_SCL)",
      "isAnalog": false,
      "isI2C": true,
      "isPWM": true
    },
    {
      "Pin": 61,
      "Name": "PB9 (I2C0_SDA)",
      "isAnalog": false,
      "isI2C": true,
      "isPWM": true
    },
    {
      "Pin": 62,
      "Name": "PE0",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": false
    },
    {
      "Pin": 63,
      "Name": "PE1",
      "isAnalog": false,
      "isI2C": false,
      "isPWM": false
    },
    {
      "Pin": 64,
      "Name": "PA0 (ADC0_IN0)",
      "isAnalog": true,
      "isI2C": false,
      "isPWM": true
    },
    {
      "Pin": 65,
      "Name": "PC3 (ADC0_IN13)",
      "isAnalog": true,
      "isI2C": false,
      "isPWM": false
    },
    {
      "Pin": 66,
      "Name": "PA5 (ADC0_IN5)",
      "isAnalog": true,
      "isI2C": false,
      "isPWM": false
    },
    {
      "Pin": 67,
      "Name": "PA2 (ADC0_IN2)",
      "isAnalog": true,
      "isI2C": false,
      "isPWM": true
    },
    {
      "Pin": 68,
      "Name": "PC0 (ADC0_IN10)",
      "isAnalog": true,
      "isI2C": false,
      "isPWM": false
    },
    {
      "Pin": 69,
      "Name": "PA3 (ADC0_IN3)",
      "isAnalog": true,
      "isI2C": false,
      "isPWM": true
    },
    {
      "Pin": 70,
      "Name": "PC2 (ADC0_IN12)",
      "isAnalog": true,
      "isI2C": false,
      "isPWM": false
    },
    {
      "Pin": 71,
      "Name": "PB0 (ADC0_IN8)",
      "isAnalog": true,
